[programs.localnet]
anchor_hello_world = "9geYrYQ8fGtj7sZsrpkNb1A73JboqbPUzw3tC2rZCpPA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
